# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Betty Steger - Software Developer"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Betty Steger, MSc. Web / Software Developer. Working remote. Self-employed and happy."


# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: assets/css
  style: compressed

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://bettysteger.com"

# The shortname for your Disqus site to enable comments.
disqus: "bettysteger"

# Author information - author info at the bottom of the post
author_name: "BETTINA STEGER"

# Social links in the site footer
twitter_username: "lpsBetty"
facebook_username: "lpsBetty"
github_username: "lpsbetty"
linkedin_username: "bettina-steger-2ab1457b"
email: "hello@bettysteger.com"

permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge

gems:
  - jekyll-gravatar
  - jekyll-redirect-from
  - jekyll-bootstrap-sass

bootstrap:
  assets: true