# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge
gems:
  - jekyll-paginate
  - jekyll-gravatar
  - jekyll-redirect-from

paginate: 5
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: bettysteger.com
description: "Bettina Steger, MSc. Web / Software Developer. Working remote. Self-employed and happy."
keywords: "Bettina Steger, web development, frontend, software engineer, software developer"
url: https://bettysteger.com
# baseurl: ""

google_analytics: UA-25710155-2
disqus_site_shortname: "bettysteger"

# Author settings
author:
  # name      : Bettina Steger
  # job       : Frontend Engineer
  # thumb     : /images/author.jpg
  email     : hello@bettysteger.com
  url       : https://bettysteger.com
  github    : https://github.com/lpsBetty
  twitter   : https://twitter.com/lpsBetty
  # facebook  : http://facebook.com/lpsBetty
  # linkedin  : http://linkedin.com/in/bettysteger

# navbar pages
navbar:
  - slug: /projects/
    title: Projects
  - slug: /blog/
    title: Blog
  - slug: /contact/
    title: Contact

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]